src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\DBAL\Types\Types;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;
use App\Entity\Service;

#[ORM\Entity(repositoryClass: ReservationRepository::class)]
class Reservation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_debut = null;
    
    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_fin = null;
    

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Veuillez Remplir Ce Champs*")]
    private ?string $categorie = null;

    #[ORM\ManyToOne(inversedBy: 'reservations')]
    #[Assert\NotBlank(message: "Veuillez Remplir Ce Champs*")]
    private ?Service $service_desiree = null;

    public function __construct()
    {
        $this->date_debut = new \DateTime('now');
        $this->date_fin = new \DateTime('now');
    }
    public function __toString()
    {
        return $this->service_desiree ? $this->service_desiree->getNom() : '';
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(?\DateTimeInterface $date_debut): static
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(?\DateTimeInterface $date_fin): static
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->categorie;
    }

    public function setCategorie(string $categorie): static
    {
        $this->categorie = $categorie;

        return $this;
    }

    //FUNCTION
    public function validateDate(ExecutionContextInterface $context, $payload)
    {
        if ($this->date_debut < new \DateTime('now')) {
            $context->buildViolation('La date de début ne peut pas être antérieure à aujourd\'hui.')
                ->atPath('date_debut')
                ->addViolation();
        }

        if ($this->date_fin < new \DateTime('now')) {
            $context->buildViolation('La date de fin ne peut pas être antérieure à aujourd\'hui.')
                ->atPath('date_fin')
                ->addViolation();
        }
    }

    public function getServiceDesiree(): ?Service
    {
        return $this->service_desiree;
    }

    public function setServiceDesiree(?Service $service_desiree): static
    {
        $this->service_desiree = $service_desiree;

        return $this;
    }

}

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Reservation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Entity\Service;

class ReservationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_debut')
            ->add('date_fin')
            ->add('categorie')
            ->add('service_desiree', EntityType::class, [
                'class' => Service::class,
                'choice_label' => 'nom', // Remplacez 'name' par la propriété que vous souhaitez afficher
                'label' => 'Service désiré', // Libellé personnalisé
                // Autres options...
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
        ]);
    }
} 

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Reservation;
use App\Form\ReservationType;
use App\Repository\ReservationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/reservation')]
class ReservationController extends AbstractController
{
    #[Route('/', name: 'app_reservation_index', methods: ['GET'])]
    public function index(ReservationRepository $reservationRepository): Response
    {
        return $this->render('reservation/index.html.twig', [
            'reservations' => $reservationRepository->findAll(),
        ]);
    }
    #[Route('/front', name: 'app_reservation_indexFront', methods: ['GET'])]
    public function indexFront(ReservationRepository $reservationRepository): Response
    {
        return $this->render('reservation/frontres.html.twig', [
            'reservations' => $reservationRepository->findAll(),
        ]);
    }
    #[Route('/new', name: 'app_reservation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $reservation = new Reservation();
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($reservation);
            $entityManager->flush();

            return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reservation/new.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }
    #[Route('/newf', name: 'app_reservation_new', methods: ['GET', 'POST'])]
    public function newf(Request $request, EntityManagerInterface $entityManager): Response
    {
        $reservation = new Reservation();
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($reservation);
            $entityManager->flush();

            return $this->redirectToRoute('app_reservation_indexFront', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reservation/newf.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reservation_show', methods: ['GET'])]
    public function show(Reservation $reservation): Response
    {
        return $this->render('reservation/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_reservation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Reservation $reservation, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reservation/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reservation_delete', methods: ['POST'])]
    public function delete(Request $request, Reservation $reservation, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reservation->getId(), $request->request->get('_token'))) {
            $entityManager->remove($reservation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/reservation/_delete_form.html.twig
<form method="post" action="{{ path('app_reservation_delete', {'id': reservation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reservation/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/reservation/edit.html.twig
{% extends 'dashboard.html.twig' %}

{% block title %}Edit Reservation{% endblock %}

{% block body %}
    <h1>Edit Reservation</h1>

    {{ include('reservation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_reservation_index') }}">back to list</a>

    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}

templates/reservation/frontres.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="service">
        <div class="container">
            <div class="section-header text-center">
                <div id="google_translate_element"></div>
                <h4 style="margin-top:50px; margin-bottom:50px;">Liste des reservations</h4>
                <a href="{{ path('app_service_indexFront') }}">Aller à la liste des services</a>
                <a href="{{ path('app_reservation_new') }}">Ajouter Reservation</a>
                <a href="{{ path('app_reclamation_new') }}">Ajouter Reclamation</a>


            </div>
            <div class="row">
        {% for reservation in reservations %}
                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="service-item">
                        <p><strong style="color:#696969">Date Debut </strong> {{ reservation.getDateDebut() ? reservation.getDateDebut()|date('Y-m-d') : '' }}</p>
                        <p><strong style="color:#696969">Date Fin </strong> {{ reservation.getDateDebut() ? reservation.getDateDebut()|date('Y-m-d') : '' }}</p>
                        <p><strong style="color:#696969">Categorie </strong> {{ reservation.categorie() }}</p>
                        <p><strong style="color:#696969">Service </strong> {{  reservation.getServiceDesiree().getNom() }}</p>

                        </div>
                    </div>
                {% else %}
                    <div class="col">
                        <p class="text-center">Aucune Reservation trouvé.</p>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <br>
{% endblock %}

templates/reservation/index.html.twig
{% extends 'dashboard.html.twig' %}


{% block body %}
	<!-- ======================= Start Dashboard ===================== -->
		<section class="dashboard gray-bg padd-0 mrg-top-50">
			<div class="container-fluid">
				<div class="row">
					
					<div class="col-lg-2 col-md-2 col-sm-3 dashboard-bg">
						<!-- /. NAV TOP  -->
							<nav class="navbar navbar-side">
							<!-- Start Logo Header Navigation -->
							<div class="navbar-header">
								<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#dashboard-menu">
									<i class="fa fa-bars"></i>
								</button>
							</div>
							<div class="collapse sidebar-collapse" id="dashboard-menu">
								<div class="profile-wrapper">
									<div class="profile-wrapper-thumb">
										<img src="assets/img/user-3.jpg" class="img-responsive img-circle" alt="" />
										<span class="dashboard-user-status bg-success"></span>
									</div>
									<h4>Duke Daniel</h4>
								</div>
								<ul class="nav" id="main-menu">
									
									<li class="active">
										<a href="dashboard.html"><i class="fa fa-dashboard" aria-hidden="true"></i>Dashboard</a>
									</li>
									
									<li>
										<a href="messages.html"><i class="ti-email" aria-hidden="true"></i>Messages</a>
									</li>
									
									<li>
										<a href="javascript:void(0)"><i class="fa fa-clone" aria-hidden="true"></i>Manage Listing <span class="fa arrow"></span></a>
										<ul class="nav nav-second-level">
											
											<li>
												<a href="manage-hotels.html"><i class="fa fa-circle-o-notch" aria-hidden="true"></i>Manage Hotels</a>
											</li>
											<li>
												<a href="manage-tours.html"><i class="fa fa-circle-o-notch" aria-hidden="true"></i>Manage Tours</a>
											</li>
										   <li>
												<a href="manage-destinations.html"><i class="fa fa-circle-o-notch" aria-hidden="true"></i>Manage Destinations</a>
											</li>
											<li>
												<a href="manage-restaurants.html"><i class="fa fa-circle-o-notch" aria-hidden="true"></i>Manage Restaurants</a>
											</li>
										</ul>
									</li>
									
									<li>
										<a href="javascript:void(0)"><i class="ti-location-pin" aria-hidden="true"></i>Add Listings <span class="fa arrow"></span></a>
										<ul class="nav nav-second-level">
											
											<li>
												<a href="http://themezhub.com/"><i class="fa fa-circle-o-notch" aria-hidden="true"></i>Add Hotels</a>
											</li>
											<li>
												<a href="add-tours.html"><i class="fa fa-circle-o-notch" aria-hidden="true"></i>Add Tours</a>
											</li>
										   <li>
												<a href="add-destinations.html"><i class="fa fa-circle-o-notch" aria-hidden="true"></i>Add Destinations</a>
											</li>
											<li>
												<a href="add-restaurants.html"><i class="fa fa-circle-o-notch" aria-hidden="true"></i>Add Restaurants</a>
											</li>
										</ul>
									</li>
									
									<li>
										<a href="invoice.html"><i class="fa-print" aria-hidden="true"></i>Invoice</a>
									</li>
									
									<li>
										<a href="javascript:void(0)"><i class="ti-calendar" aria-hidden="true"></i>My Booking <span class="fa arrow"></span></a>
										<ul class="nav nav-second-level">
											<li>
												<a href="booking-1.html"><i class="fa fa-circle-o-notch" aria-hidden="true"></i>Booking 1</a>
											</li>
											<li>
												<a href="booking-2.html"><i class="fa fa-circle-o-notch" aria-hidden="true"></i>Booking 2</a>
											</li>
										</ul>
									</li>
									
									<li>
										<a href="javascript:void(0)"><i class="fa fa-cog" aria-hidden="true"></i>Settings <span class="fa arrow"></span></a>
										<ul class="nav nav-second-level">
											<li>
												<a href="basic-settings.html"><i class="fa fa-circle-o-notch" aria-hidden="true"></i>Basic Settings</a>
											</li>
											<li>
												<a href="site-settings.html"><i class="fa fa-circle-o-notch" aria-hidden="true"></i>Site Settings</a>
											</li>
										</ul>
									</li>
									
									<li>
										<a href="my-profile.html"><i class="ti-user" aria-hidden="true"></i>My Profile</a>
									</li>
									
									<li>
										<a href="add-payment-methode.html"><i class="ti-credit-card" aria-hidden="true"></i>Add Payment Methode</a>
									</li>
									
									<li class="log-off">
										<a href="login.html"><i class="fa fa-power-off" aria-hidden="true"></i>Logout</a>
									</li>
								</ul>
							</div>
						</nav>
						<!-- /. NAV SIDE  -->
					</div>
					
					<div class="col-lg-10 col-md-10 col-sm-9 col-lg-push-2 col-md-push-2 col-sm-push-3">
						<div class="row mrg-0 mrg-top-20">
							<div class="tr-single-box">
								<div class="tr-single-header">
									<h3 class="dashboard-title">Dashboard</h3>
								</div>
								<div class="tr-single-body">
								<fieldset>
    <br><br><br>
    <div class="container">
        <div class="row">
            <div class="col-md-10 offset-md-1">
                <h1 class="text-center mb-4">Liste des reservations</h1>
   <table class="table table-bordered table-hover table-sm">
    <thead class="thead-dark">        <thead>
            <tr>
                <th>Id</th>
                <th>Date Debut</th>
                <th>Date fin</th>
                <th>Categorie</th>
                <th>Service</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for reservation in reservations %}
            <tr>
                <td>{{ reservation.getId }}</td>
                <td>{{ reservation.categorie }}</td>
                <td>{{ reservation.getDateDebut ? reservation.getDateDebut|date('Y-m-d') : '' }}</td>
                <td>{{ reservation.getDateFin ? reservation.getDateFin|date('Y-m-d') : '' }}</td>
                <td>{{ reservation.getServiceDesiree().getNom() }}</td>
                <td>
                    <a href="{{ path('app_reservation_show', {'id': reservation.id}) }}">show</a>
                    <a href="{{ path('app_reservation_edit', {'id': reservation.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_reservation_new') }}">Create new</a>
{% endblock %}

templates/reservation/new.html.twig
{% extends 'dashboard.html.twig' %}

{% block title %}New Reservation{% endblock %}

{% block body %}
    <h1>Create new Reservation</h1>

    {{ include('reservation/_form.html.twig') }}
    
    <a href="{{ path('app_reservation_index') }}">back to list</a>
{% endblock %}

templates/reservation/newf.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Reservation{% endblock %}

{% block body %}
    <h1>Create new Reservation</h1>

    {{ include('reservation/_form.html.twig') }}
    
    <a href="{{ path('app_reservation_indexFront') }}">back to list</a>
{% endblock %}

templates/reservation/show.html.twig
{% extends 'dashboard.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}
    <h1>Reservation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reservation.id }}</td>
            </tr>
            <tr>
                <th>Date debut</th>
                <td>{{ reservation.dateDebut ? reservation.dateDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ reservation.dateFin ? reservation.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Categorie</th>
                <td>{{ reservation.categorie }}</td>
            </tr>
            <tr>
                <th>Service desire</th>
                <td>{{ reservation.getServiceDesiree().getNom() }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_reservation_index') }}">back to list</a>

    <a href="{{ path('app_reservation_edit', {'id': reservation.id}) }}">edit</a>

    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}